### ISSUE TITLE
Unable to initialise due to 'find' process - pending replication & root cause

### ISSUE THREAD

**Issue by lanceteo** [tebelorg/TagUI-Python#53] opened 2019-09-11 05:07 UTC
![find_process_tagui](https://user-images.githubusercontent.com/10450460/64669573-ae896900-d494-11e9-83f8-f172822cf14d.png)

I am unable to initialise tagui. I found out the issue is due to a process called 'find' after attempting to intialise. I tried killing the 'find' process and it works. But I don't think it is efficient to do this everytime.

Am I doing something wrong that caused this?

I have tried to re-install and/or upgrade tagui, but issue still persists.

Please see attached screenshot for the 'find' process.

**Comment by kensoh** [comment] 2019-09-11 15:59
Hi Lance, thanks for these details! I have not encountered this problem before. `find.exe` is a command used during launching TagUI process. Usually this type of weird problems happen due to anti-virus / firewall by company laptop. Can you try 2 things and let me know -

1. try installing TagUI for Python on another laptop, your personal laptop or someone you know, which is not a company laptop with in-built firewall / virus-scanning policies. this tries to isolate if the issue is related to company laptop.

2. go to your %APPDATA% folder, I think from command prompt you can do cd %APPDATA% - after that go to tagui\unx folder. try typing `find /i /c "345" "find.exe"` to see what happens. this tries to trigger the whatever problem that's causing find to hang.

**Comment by kensoh** [comment] 2019-09-17 04:16
Closing issue or now until further inputs from Lance or other users

**Comment by lanceteo** [comment] 2019-09-17 04:25
Hi Ken, sorry for the late reply. Just realised after you closed the issue.

1. I have tried on my personal computer and it does not have this issue.
2. The weird thing is I do not have "find.exe" within the directory that you mentioned, and my directory is slightly different (tagui\src\unx). I tried searching the whole directory of tagui and could not find "find.exe".

Attached screenshot of what are available in tagui\src\unx.
![image](https://user-images.githubusercontent.com/10450460/65011460-2dbfe680-d946-11e9-8ab4-93c08a6453e4.png)

**Comment by kensoh** [comment] 2019-09-17 06:42
Hi Lance, no probs! Let me reopen the issue.

1. Great, that helps to further isolate the root cause, that its only happening on your work PC.

2. I just checked again, find.exe is supposed to come with Windows. Try going to the tagui\src folder to run this command to see what happens - `find /i /c "RPA" "tagui.cmd"`

Hopefully that can replicate the issue that cause the find command to hang, so that we can look at solving the root cause. If the root cause cannot be found, there is a way to hack tagui\src\tagui.cmd to comment out the line that use find command.

This will work for you, but not recommended. Because every time you upgrade to a new version, your hacked change will be overwritten and have to do again.

**Comment by kensoh** [comment] 2019-09-17 06:59
(sorry for the wrong command to test earlier. I mixed up find.exe thinking it is one of the files I packaged together with TagUI but it actually comes with Windows).

**Comment by lanceteo** [comment] 2019-09-20 07:41
Hi Ken,

This is my directory for Python: "D:\Users\lance.teo\AppData\Local\Continuum\anaconda3\pythonw.exe" 
I could not find tagui_python.js in this directory nor in the ~scripts folder.
Is this the cause of the problem?

Yes, I have read/write permission, but no admin rights.

I have no issue with other packages though. I have been using Python on this particular work laptop for the past 2 months.

**Comment by kensoh** [comment] 2019-09-21 05:58
Hi Lance, you miss out 2 questions I asked above, can you tell me more about these?

>did the find command hang there, or it returns back control to the command prompt?

>Can you tell me the exact steps that you take to launch TagUI for Python?

In addition, can you try running the following and see what happens?
```py
import os
import tagui as t
os.chdir('D:\Users\lance.teo\Desktop')
t.init()
t.url('https://github.com/tebelorg/TagUI-Python')
t.click('Clone or download')
t.click('Download ZIP')
t.wait()
t.close()
```

Above tries to switch the current folder to your Windows Desktop, before starting the TagUI process. See if the find command still hangs the whole automation. If it still hangs, try running below command from Anaconda command prompt while it is still hanging to see what happens -

```
cd D:\Users\lance.teo\Desktop
find /i /c "api http" "tagui_python.js"
```

**Comment by kensoh** [comment] 2019-10-10 02:22
Closing issue for now until further inputs!

**Closed by kensoh** 2019-10-10 02:22 UTC
Labels: query
