### ISSUE TITLE
Different behaviour in TagUI write and TagUI for Python write() - by design

### ISSUE THREAD

**Issue by ck81** [tebelorg/TagUI-Python#44] opened 2019-08-12 01:22 UTC
Hi Ken,

Just tried some `write()` in TagUI-Python

Found out that 
- `write` in TagUI automatically includes new line at the end of the write string
- `write()` in TagUI-Python does not

Can I confirm the above behaviour?

Would be great if the two can be standardized - so that it's easier for people who need to port scripts from TagUI to TagUI-Python.

**Comment by kensoh** [comment] 2019-08-12 11:19
Hi CK, yes you are right! The behaviour is intentional and by design.

It can't be standardised because the target users for both projects are different. TagUI is meant more for business users and non-developers, so things are done as much as possible to simplify tasks for them. This includes automatically inserting line break '\r\n' for write step.

However, TagUI for Python is meant more for Python users. Thus write() step cannot automatically add the line break characters '\r\n' as that means users cannot write a series of strings to a file sequentially without inserting line breaks in between. That would be very un-Pythonic and non-standard programming language behaviour.

In the interim, for TagUI users who want to port to TagUI for Python, they will face this difference. Workaround will be inside the write() function in tagui.py (search for `def write(`), change the following line

```py
write_output_file.write(_py23_write(text_to_write)
```

to something like

```py
write_output_file.write(_py23_write(text_to_write + '\r\n')
```

This seems hacky, but if standardise the two, the group of Python users using this package directly, compared to existing TagUI users who port to Python, will be a much larger group. And they can't be paying the price to address the the smaller group's needs. If change TagUI write to be without '\r\n' it will also break backward compatibility of its existing user scripts, thus not a suitable solution.

**Comment by ck81** [comment] 2019-08-13 12:22
Hi Ken,

Thanks for the detailed explanation.  Know where you're coming from.

This is not a big issue in python, because it's now very easy to little function in python to automatically add a "\n" at the end of each write.

You may want to highlight this in your documentation for TagUI-Python though.  I'm sure there will some users like me trying to port TagUI script into TagUI-Python and bump into this wondering what's happening.

**Comment by kensoh** [comment] 2019-08-13 15:53
That's a good suggestion CK. From your experience so far, other than write() and visible(), have you experienced other differences in behaviour between TagUI for Python functions and TagUI steps that would help to be documented?

**Comment by kensoh** [comment] 2019-08-20 00:08
Closing this as CK created a new issue #47 with details of the comparison!

**Closed by kensoh** 2019-08-20 00:08 UTC
Labels: query
