### ISSUE TITLE
Error using run() on Windows - for eg run("cmd /c dir") [fixed]

### ISSUE THREAD

**Issue by ck81** [tebelorg/TagUI-Python#46] opened 2019-08-17 02:23 UTC
Hi Ken,

Tried to run a DOS command using your suggestion in: https://github.com/kelaberetiv/TagUI/issues/473

The following works in TagUI:
```
run cmd /c dir
echo run_result
```

In TagUI-Python on windows 10:
```
run_result = t.run("cmd /c dir")
print("run_result)
```

The above will give the error message:
```
Traceback (most recent call last):
  File "test1.py", line 2, in <module>
    run_result = t.run("cmd /c dir")
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tagui.py", line 1173, in run
    shell=True))
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'cmd /c dir; exit 0' returned non-zero exit status 1.
```

**Comment by kensoh** [comment] 2019-08-18 02:23
Hi CK, thanks for raising this! May need your help to test because I don't have access to a Windows laptop now. Issues #45 #46 should be related to the same cause.

The best practice for running commands from Python using subprocess requires using the exit 0 to be always appended. This is to capture error messages if the command results in error -
https://docs.python.org/3.4/library/subprocess.html?highlight=exp#subprocess.check_output

Below shows a replication case if exit 0 is not appended and what happens if appended. When it is not appended as part of the command, if the command returns error it will raise a Python exception with error code instead of showing the error message which is more meaningful for debugging.

```
>>> t.run('abc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tagui.py", line 1173, in run
    shell=True))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'abc' returned non-zero exit status 127

>>> t.run('abc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tagui.py", line 1173, in run
    shell=True))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'abc' returned non-zero exit status 127
>>> t.run('abc; exit 0')
'/bin/sh: abc: command not found\n'
```

Will dig further. There may not be a solution or the solution could be not appending for echo commands. For the cmd error, looks like it is some other cause.

**Comment by kensoh** [comment] 2019-08-18 02:43
For echo on macOS, it looks alright with appending exit 0. 

```
>>> t.run('echo 123; exit 0')
'123\n'
```

**Comment by kensoh** [comment] 2019-08-18 02:43
On macOS, the ; works in echo as a delimiter for next command. From your above example, it looks like for Windows, the ; is not recognised by echo as a delimiter. Thus the `;exit 0` string becomes part of the echo output result when you run echo.

```
Tebel:tagui-python kensoh$ echo 123; echo 456
123
456
```

**Comment by kensoh** [comment] 2019-08-18 02:43
Solution may be to use `&` when run() is invoked on Windows environment. I'll have to borrow a Windows laptop and test on this.

https://stackoverflow.com/questions/8055371/how-do-i-run-two-commands-in-one-line-in-windows-cmd

**Comment by kensoh** [comment] 2019-08-18 23:32
The issue should have the same root cause at #45 - probably the ; gets interpreted as part of the command resulting in the error message, will check on this when I borrow a Windows laptop.

**Comment by kensoh** [comment] 2019-08-20 00:05
Going to update run() to below, tested ok on Windows. Will test on macOS and Linux before patching -

```py
def run(command_to_run = None):
    if command_to_run is None or command_to_run == '':
        print('[TAGUI][ERROR] - command(s) missing for run()')
        return ''

    else:
        if platform.system() == 'Windows':
            command_delimiter = ' & '
        else:
            command_delimiter = '; '
        return _py23_decode(subprocess.check_output(
            command_to_run + command_delimiter + 'exit 0',
            stderr=subprocess.STDOUT,
            shell=True))
```

**Comment by kensoh** [comment] 2019-08-20 02:51
This is now fixed in v1.10 - to upgrade, using `pip install tagui --upgrade`

Thank you very much @ck81 for spotting this and raising this issue!

**Comment by ck81** [comment] 2019-08-27 15:45
Hi Ken,

Just downloaded the latest version.

Yes, the following now run's perfectly ok now.

~~~python
run_result = t.run("cmd /c dir")
print("run_result)
~~~

Thanks for the fix!

**Comment by kensoh** [comment] 2019-08-27 15:51
Thanks CK for your update! I appreciate very much that you spotted this and feedback.

**Closed** 2019-08-28 00:05 UTC
Labels: bug
