### ISSUE TITLE
MSVCR110.dll not found on Windows - see this issue for the solution to fix

### ISSUE THREAD

**Issue by EnriqueBet** [tebelorg/TagUI-Python#38] opened 2019-07-16 16:46 UTC
I have tried to run a simple script to navigate into a website in python. Aparently tagUi is not able to initalize due to a missing MSVCR100.dll dependency.

I have tried to reinstall the package with this link: https://www.microsoft.com/en-us/download/confirmation.aspx?id=14632

After reinstallation and reboting my machine, the result is the same. I am using python with Anaconda and Windows 10, probably is because of this?

Thanks!
![Captura](https://user-images.githubusercontent.com/20655381/61313031-3584d280-a7bf-11e9-92f5-eecefea54f88.PNG)

**Comment by kensoh** [comment] 2019-07-17 02:41
Hi @EnriqueBet, TagUI for Python will try to auto-download and run the setup for this.

But if it fails to automatically download and start the setup, do you see the following message?

```
[TAGUI][INFO] - MSVCR110.dll is still missing, install vcredist_x86.exe from
[TAGUI][INFO] - https://www.microsoft.com/en-us/download/details.aspx?id=30679
[TAGUI][INFO] - after that, TagUI ready for use in your Python environment
```

1. Can you try installing using https://www.microsoft.com/en-us/download/details.aspx?id=30679

2. If that does not work, can you try the suggestions in issue https://github.com/tebelorg/TagUI-Python/issues/39? The error can happen if there is a previous installation which was removed but was not removed cleanly.

https://blogs.msdn.microsoft.com/vsnetsetup/2014/07/17/installation-failing-with-a-newer-version-of-microsoft-visual-c-2010-redistributable-has-been-detected-on-this-machine/

If above still do not work, please post here so we can look at it together and solve the problem!

**Comment by kensoh** [comment] 2019-07-17 02:55
Hi @EnriqueBet, adding on to above, before you try the steps above, can you run the following Python script and let me know what is the output? I use the following code to detect for missing MSVCR110.dll but I don't have a Windows laptop that has this issue to actually test if this logic is correct.

```py
import os
print(os.system(os.environ['APPDATA'] + '/' + 'tagui' + '/' + 'src' + '/' + 'php/php.exe -v > nul 2>&1'))
```

**Comment by EnriqueBet** [comment] 2019-07-17 15:22
Hi @kensoh, thanks for your help. I have tried the code that you post, the results was the same the pop up window appeared and the print output was:
**-1073741515**

So I believe the next step is to try your first suggestion.

Thanks! I will let you know how does it evolves.

**Comment by kensoh** [comment] 2019-07-17 16:01
Sure @EnriqueBet thanks for your update! Will look out for how it evolves.

Also, do you get message like below after you see the PHP error message?

```
[TAGUI][INFO] - now installing missing Visual C++ Redistributable dependency
```

```
[TAGUI][INFO] - MSVCR110.dll is still missing, install vcredist_x86.exe from
[TAGUI][INFO] - https://www.microsoft.com/en-us/download/details.aspx?id=30679
[TAGUI][INFO] - after that, TagUI ready for use in your Python environment
```

**Comment by kensoh** [comment] 2019-07-25 16:13
Closing issue for time being until further inputs from Enrique or other users!

**Closed by kensoh** 2019-07-25 16:13 UTC
Labels: query

**Comment by Lmac99** [comment] 2020-05-19 21:33
Hi @kensoh.
I was using RPA-Python for some time, but recently i switched to another pc and the same error occured. I'm sending some images and hope to get over this problem.

Here is an image from VsCode
![image](https://user-images.githubusercontent.com/37408996/82379880-a4414680-99f5-11ea-9bfa-c92f548b7b7c.png)

If i delete the tagui folder  and try to run the script again
![image](https://user-images.githubusercontent.com/37408996/82380447-76a8cd00-99f6-11ea-8f57-29bcf7de4baf.png)

full image
![image](https://user-images.githubusercontent.com/37408996/82380683-e15a0880-99f6-11ea-9631-98ca72f64ef0.png)

**Comment by Lmac99** [comment] 2020-05-19 21:55
Update.

After installing the version x86 of the vcredist downloaded at microsoft site it worked. So we can conclude it's not about the system version (x64 in my case)

**Comment by kensoh** [comment] 2020-05-20 17:16
Hi @Lmac99 you have found the root cause. Yes the x86 version is required, and the package will inform you of the link to download (as shown in your above attached image), if that MSVCR110.dll file is missing.

What might have cause this perhaps is you might have copied the folder directly to another computer, so the initial auto-setup was never ran and you didn't see the error message above. Until you deleted the folder and run again.

**Comment by israelfc92** [comment] 2023-04-19 15:31
Efectivamente funciona con la versión x86, esto al menos en una maquina x64, windows 10. Antes de la instalación de la versión x86 se quito la versión x64.

https://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x86.exe
