### ISSUE TITLE
[TAGUI][ERROR] - failed downloading from.. macOS + Python 3 issue [fixed]

### ISSUE THREAD

**Issue by cevangelio** [tebelorg/TagUI-Python#6] opened 2019-06-20 23:44 UTC
I was able to install tagui using pip but is unable to start it. t.init() gives 

```
[TAGUI][INFO] - setting up TagUI for use in your Python environment
[TAGUI][INFO] - downloading TagUI (~200MB) and unzipping to below folder...
[TAGUI][INFO] - /Users/my_id
[TAGUI][ERROR] - failed downloading from https://github.com/tebelorg/Tump/releases/download/v1.0.0/TagUI_macOS.zip
False
```

I am sure I am connected to the internet and I was able to manually download the file (TagUI_macOS.zip). Unzipped to the location but getting same error. Any workarounds?

**Comment by cevangelio** [comment] 2019-06-20 23:55
Manually moved tagui to ~/.tagui and it worked.

**Comment by kensoh** [comment] 2019-06-21 00:09
Hi @cevangelio thanks for raising this issue! Can you help run the code below to see what is the cause of the error message? So that I can fix it for future downloads by users.

Below code uses the correct urllib for Python 2 or 3 to do the download. I didn't expect anything can go wrong for something as straightforward as this, so I didn't print the actual exception error e.

```py
import tagui as t
tagui_zip_file = 'TagUI_macOS.zip'
tagui_zip_url = 'https://github.com/tebelorg/Tump/releases/download/v1.0.0/' + tagui_zip_file

import os
home_directory = os.path.expanduser('~')

download_url = tagui_zip_url
filename_to_save = home_directory + '/' + tagui_zip_file

if t._python2_env():
    import urllib; urllib.urlretrieve(download_url, filename_to_save)
else:
    import urllib.request; urllib.request.urlretrieve(download_url, filename_to_save)
```

**Comment by kensoh** [comment] 2019-06-21 00:17
There are also some other auto-setup actions done for macOS which may be missed if the downloading and unzipping is done manually, eg setting up of OpenSSL. And that may cause execution error.

**Comment by kensoh** [comment] 2019-06-21 01:30
In the meantime, reopening issue for a code change for a more informative error message.

```py
print('[TAGUI][ERROR] - failed downloading from ' + download_url + '...')
print(str(e))
```

**Comment by cevangelio** [comment] 2019-06-21 05:33
Here you go. 

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>`

**Comment by kensoh** [comment] 2019-06-21 17:02
Thanks @cevangelio, looks like an issue with Python 3 on macOS where users have to manually install certificates. Will take a look to see if can automate this setup to run the Python 3 `Install Certificates.command` script to allow access to https:// endpoints.

https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error
https://stackoverflow.com/questions/44649449/brew-installation-of-python-3-6-1-ssl-certificate-verify-failed-certificate

**Comment by kensoh** [comment] 2019-06-21 17:16
In the interim, macOS users facing the error can fix this by going to -

`Applications --> Python 3.x --> Install Certificates.command`

**Comment by kensoh** [comment] 2019-06-22 10:15
Made a commit with below comments. `pip install tagui --upgrade` or new installations should now work. There will be auto-setup of SSL certs for users who downloaded Python 3 installation from Python website. For Anaconda or brew installations, this issue may still happen, will look out and make new code checks as needed.

>#6 - on macOS with Python 3, there is no SSL certs support by default. adding an additional check to auto-install SSL certs. before this change, download() simply fails.
>
>#7 - adding capability to autosync tagui delta files when new tagui for python releases are installed. this lets users immediately access current features when they do a pip install tagui --upgrade. before this change, t.setup() is needed for existing installations.
>
>#7 - upstream fix implemented for snapshots of web elements on Chrome. fix improves performance and quality base on newer DevTools Protocol capabilities. the fix is accessible when users do a pip install tagui --upgrade. before this change, snap() captures screenshot of the whole webpage instead of only the element.

**Comment by kensoh** [comment] 2019-06-28 15:55
Closing issue for now, until new data points from users to automate installation for other setups.

**Closed by kensoh** 2019-06-28 15:55 UTC
Labels: query

**Comment by oai1228** [comment] 2019-10-08 04:40
[TAGUI][ERROR] - 'utf-8' codec can't decode byte 0x80 in position 65: invalid start byte
what is wrong?

**Comment by oai1228** [comment] 2019-10-08 04:41
import tagui as t
t.init()
[TAGUI][ERROR] - 'utf-8' codec can't decode byte 0x80 in position 65: invalid start byte
what is wrong?

**Comment by kensoh** [comment] 2019-10-10 01:52
Hi @oai1228, I haven't encounter this issue before and other users too. In an issue few months back, I made an enhancement to make the default encoding UTF-8 for Python 2 and Python 3 (https://github.com/tebelorg/TagUI-Python/issues/14), that should handle issues with encoding compatibility.

But I'm not sure how to replicate your error above. Can you try on another laptop or environment to see if that works, and then find out more the difference in the laptop and let me know more? 

This package is supposed to run ok on Windows, macOS, Linux, Python 2 and 3, and on operation systems based in different languages. There might be some edge case where other users have not encountered which you spotted. If there are more details I can try to figure out what is the problem.

Thanks!

**Comment by oai1228** [comment] 2019-10-14 02:25
Hi, Thank you for your answer, I know that this module does not fit in korean.
Decode and Encode are not working well

**Comment by kensoh** [comment] 2019-10-14 02:49
Thanks @oai1228, sorry about that.

If you or your friends have ideas how to improve the code to support Korean let me know.

**Comment by bing086** [comment] 2020-02-15 05:11
[RPA][INFO] - setting up TagUI for use in your Python environment
[RPA][INFO] - downloading TagUI (~200MB) and unzipping to below folder...
[RPA][INFO] - /Users/wlb
[RPA][ERROR] - failed downloading from https://github.com/tebelorg/Tump/releases/download/v1.0.0/TagUI_macOS.zip...
[Errno 54] Connection reset by peer
[RPA][INFO] - setting up TagUI for use in your Python environment
[RPA][INFO] - downloading TagUI (~200MB) and unzipping to below folder...

**Comment by kensoh** [comment] 2020-02-15 07:37
Hi @bing086 this error happens when your computer cannot access the GitHub URL to download files required by the package to work.

Can you check your network or firewall policy to see if the access is blocked. If there is no way to access, you can try VPN or another computer which can access the files from Github URLs, then use r.pack() to create a zip, so that you can copy to your computer to do installation without internet.

**Comment by Mavericks334** [comment] 2021-07-27 12:44
Hi @kensoh 
I get the below error on Windows.
SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)

**Comment by Mavericks334** [comment] 2021-07-27 12:46
Hi @kensoh,

This is the error i get in Windows.

```
SSLCertVerificationError                  Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\urllib\request.py in do_open(self, http_class, req, **http_conn_args)
   1318                 h.request(req.get_method(), req.selector, req.data, headers,
-> 1319                           encode_chunked=req.has_header('Transfer-encoding'))
   1320             except OSError as err: # timeout error

C:\ProgramData\Anaconda3\lib\http\client.py in request(self, method, url, body, headers, encode_chunked)
   1251         """Send a complete request to the server."""
-> 1252         self._send_request(method, url, body, headers, encode_chunked)
   1253 

C:\ProgramData\Anaconda3\lib\http\client.py in _send_request(self, method, url, body, headers, encode_chunked)
   1297             body = _encode(body, 'body')
-> 1298         self.endheaders(body, encode_chunked=encode_chunked)
   1299 

C:\ProgramData\Anaconda3\lib\http\client.py in endheaders(self, message_body, encode_chunked)
   1246             raise CannotSendHeader()
-> 1247         self._send_output(message_body, encode_chunked=encode_chunked)
   1248 

C:\ProgramData\Anaconda3\lib\http\client.py in _send_output(self, message_body, encode_chunked)
   1025         del self._buffer[:]
-> 1026         self.send(msg)
   1027 

C:\ProgramData\Anaconda3\lib\http\client.py in send(self, data)
    965             if self.auto_open:
--> 966                 self.connect()
    967             else:

C:\ProgramData\Anaconda3\lib\http\client.py in connect(self)
   1421             self.sock = self._context.wrap_socket(self.sock,
-> 1422                                                   server_hostname=server_hostname)
   1423 

C:\ProgramData\Anaconda3\lib\ssl.py in wrap_socket(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, session)
    422             context=self,
--> 423             session=session
    424         )

C:\ProgramData\Anaconda3\lib\ssl.py in _create(cls, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, context, session)
    869                         raise ValueError("do_handshake_on_connect should not be specified for non-blocking sockets")
--> 870                     self.do_handshake()
    871             except (OSError, ValueError):

C:\ProgramData\Anaconda3\lib\ssl.py in do_handshake(self, block)
   1138                 self.settimeout(None)
-> 1139             self._sslobj.do_handshake()
   1140         finally:

SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)

During handling of the above exception, another exception occurred:

URLError                                  Traceback (most recent call last)
<ipython-input-4-edf91c81e1b4> in <module>
     12     import urllib; urllib.urlretrieve(download_url, filename_to_save)
     13 else:
---> 14     import urllib.request; urllib.request.urlretrieve(download_url, filename_to_save)

C:\ProgramData\Anaconda3\lib\urllib\request.py in urlretrieve(url, filename, reporthook, data)
    245     url_type, path = splittype(url)
    246 
--> 247     with contextlib.closing(urlopen(url, data)) as fp:
    248         headers = fp.info()
    249 

C:\ProgramData\Anaconda3\lib\urllib\request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    220     else:
    221         opener = _opener
--> 222     return opener.open(url, data, timeout)
    223 
    224 def install_opener(opener):

C:\ProgramData\Anaconda3\lib\urllib\request.py in open(self, fullurl, data, timeout)
    523             req = meth(req)
    524 
--> 525         response = self._open(req, data)
    526 
    527         # post-process response

C:\ProgramData\Anaconda3\lib\urllib\request.py in _open(self, req, data)
    541         protocol = req.type
    542         result = self._call_chain(self.handle_open, protocol, protocol +
--> 543                                   '_open', req)
    544         if result:
    545             return result

C:\ProgramData\Anaconda3\lib\urllib\request.py in _call_chain(self, chain, kind, meth_name, *args)
    501         for handler in handlers:
    502             func = getattr(handler, meth_name)
--> 503             result = func(*args)
    504             if result is not None:
    505                 return result

C:\ProgramData\Anaconda3\lib\urllib\request.py in https_open(self, req)
   1360         def https_open(self, req):
   1361             return self.do_open(http.client.HTTPSConnection, req,
-> 1362                 context=self._context, check_hostname=self._check_hostname)
   1363 
   1364         https_request = AbstractHTTPHandler.do_request_

C:\ProgramData\Anaconda3\lib\urllib\request.py in do_open(self, http_class, req, **http_conn_args)
   1319                           encode_chunked=req.has_header('Transfer-encoding'))
   1320             except OSError as err: # timeout error
-> 1321                 raise URLError(err)
   1322             r = h.getresponse()
   1323         except:

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)>
```

Regards,
Ren.

**Comment by kensoh** [comment] 2021-07-28 05:02
Hi Ren, saw your issue at https://github.com/tebelorg/RPA-Python/issues/287 and will follow-up there.
